@startuml
left to right direction
title диаграмма развёртывания
database Файл
node Система_поиска_ключ_слов
actor Пользователь
node ПО
node Верхняя_Панель
node Область_отправки_на_печать
node Область_редактирования

Пользователь - Область_редактирования : редактирует информацию
Область_редактирования - Файл : Сохраняет данные
Пользователь - Верхняя_Панель : запрос на действие
Верхняя_Панель - ПО : нахождение нужных функций
ПО - Файл : запрос на данные
Файл --> Область_отправки_на_печать : отправляет данные
Файл --> Система_поиска_ключ_слов : отправляет данные
@enduml