@startuml
left to right direction
title Текстовый редактор
actor Пользователь
actor Создатель

rectangle функции_редактора{
Пользователь -- (создать файл)
Пользователь -- (редактировать файл)
Пользователь -- (отправить на печать)

Создатель -- (создать специальный файл)
Создатель -- (редактировать специальный файл)
Создатель -- (отправить специальный файл на печать)

(подсветить ключевые слова)
(создать файл) .> (редактировать файл)
(создать файл) .> (отправить на печать)
(отправить на печать)

(создать специальный файл) .> (редактировать специальный файл) 
(создать специальный файл) .> (отправить специальный файл на печать) 
(отправить специальный файл на печать)
(подсветить ключевые слова) ..> (создать специальный файл)
}
@enduml

@startuml
title диаграмма классов 
class Файл{
+Текст
}
class Файл_спец_формата{
+Текст
+Ключевые слова
}
class Пользователь{
+Имя
Предоставлять файл()
}
class ПО{
+код программы
+файлы на вход
}
class Нижняя_Панель{
+ количество строк
+ количество слов
}
class Верхняя_Панель{
+ кнопки
сохранить()
сохранить как()
открыть()
создать()
печать()
}
class Панель_инструментов{
+ размер шрифта
+ цвет
найти()
заменить()
}
Файл_спец_формата --> Файл
Пользователь ..> Файл: выбирает
Файл ..> ПО: подаётся на вход
Верхняя_Панель --> ПО
Панель_инструментов --> ПО
Нижняя_Панель --> ПО
@enduml